{
    "name": "Fusion Travel",
    "summary": "Unified Odoo 19 travel booking, ticketing, portal and accounting platform",
    "version": "19.0.2.5.0",
    "category": "Services/Travel",
    "author": "Fusion Travel",
    "website": "https://fusionlc.com",
    "depends": [
        "base",
        "mail",
        "website",
        "portal",
        "sale_management",
        "account",
        "product",
    ],
    "data": [
        "security/fusion_travel_security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/email_templates.xml",
        "data/default_products.xml",
        "data/cron.xml",
        "views/travel_booking_views.xml",
        "views/travel_flight_ticket_views.xml",
        "views/travel_airline_views.xml",
        "views/travel_offer_views.xml",
        "views/travel_pricing_rule_views.xml",
        "views/travel_wallet_transaction_views.xml",
        "views/travel_api_log_views.xml",
        "views/account_move_views.xml",
        "views/res_config_settings_views.xml",
        "views/website_templates.xml",
        "views/portal_templates.xml",
        "views/travel_menu.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "fusion_travel/static/src/scss/fusion_travel.scss",
            "fusion_travel/static/src/js/fusion_travel.js",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
