from . import travel_booking
from . import travel_passenger
from . import travel_flight_segment
from . import travel_hotel_stay
from . import travel_car_service
from . import travel_pricing_rule
from . import travel_wallet_transaction
from . import travel_api_log
from . import travel_offer
from . import travel_airline
from . import travel_flight_ticket
from . import account_move
from . import res_config_settings
