{
    'name': 'Trip Booking Platform',
    'summary': 'Flights, Hotels, Cars booking platform integrated with Odoo',
    'version': '1.7.0',
    'category': 'Travel',
    'author': 'Fusion',
    'depends': [
        'base',
        'mail',
        'website',
        'portal',
        'sale_management',
        'account',
        'crm',
    ],
    'data': [
        'security/trip_security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/email_templates.xml',
        'views/trip_booking_views.xml',
        'views/trip_pricing_rule_views.xml',
        'views/trip_wallet_transaction_views.xml',
        'views/trip_api_log_views.xml',
        'views/res_config_settings_views.xml',
        'views/website_templates.xml',
        'views/portal_templates.xml',
        'views/trip_menu.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
